### ISSUE TITLE
where is the MD5.pas,SHA1.pas?

### ISSUE THREAD

**Issue by yuzun** [nikosdion/timecode#1]
where is the MD5.pas,SHA1.pas?

**Comment by nikosdion** [comment]
These are parts of [FreePascal's `hash` package](http://wiki.freepascal.org/hash). I believe they can be downloaded and compiled into Delphi just as fine. To be honest, I haven't touched that code in years. I stopped doing Delphi/FreePascal development.

**Comment by lainz** [comment]
Is not possible to compile these units as simple.
- Types that are not defined in Delphi but are defined in FPC (QWord, DWord)
- Features that are not supported in Delphi like:
`external name 'MD_FINAL'; 
[public,alias:'MD_FINAL'];`
- Need to declare 'overload' in every single function with same name, but different parameters
- A lot of methods that are part of the FPC RTL that can't be copied as simple (https://stackoverflow.com/questions/32531879/roldword-implementation-in-delphi-both-32-and-64-bit) that is one I can find, but others like NtoLE (https://www.freepascal.org/docs-html/rtl/system/ntole.html) I did not find the source in the RTL, but maybe it depends in another thing as always...
- Need to remove `{$push} {$pop}`

So I did not try anymore...

**Comment by nikosdion** [comment]
You can always replace the calls to MD5 and SHA1 with calls to the [DPCrypt library](http://www.cityinthesky.co.uk/opensource/dcpcrypt/). As I said I have stopped doing Pascal development years ago but I found that hint with a very brief Google search. I hope that helps!

**Comment by lainz** [comment]
Seems that the original project (https://github.com/wendelb/DelphiOTP) works the same as yours but in Delphi.

Maybe they fixed the stuff you noted in the readme.

At least it gives me the same tokens both in Lazarus Win32 and Delphi Win32. They seem to have an issue with Android, maybe they're using a system thing that breaks the code when used in Android (It gives me different tokens in Android).

But, your code in LAMW + Laz4Android works perfect, it gives me the same tokens as Lazarus for Win32. So you did a good job!

I see you're doing web stuff now, I'm doing that too.

Well, see you, thanks for your help!
